name: Build artifact

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  detect-file-change:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Test file change
        id: test-file-change
        uses: tj-actions/changed-files@v45
        with:
          fetch_additional_submodule_history: 'true'
          files: |
            mk/artifact.mk
            tests/ansibench/**
            tests/rv8-bench/**
            tests/doom/**
            tests/quake/**
            tests/scimark2/**
            tests/*.c
      - name: Set alias
        id: has_changed_files
        run: |
          if [[ ${{ steps.test-file-change.outputs.any_modified }} == true ]]; then
            echo "has_changed_files=true" >> $GITHUB_OUTPUT
          else
            echo "has_changed_files=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      has_changed_files: ${{ steps.has_changed_files.outputs.has_changed_files }}

  build-artifact:
    needs: [detect-file-change]
    if: ${{ needs.detect-file-change.outputs.has_changed_files == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install dependencies
        run: |
          sudo apt-get update -q=2
          sudo apt-get upgrade -q=2
          sudo apt-get install -q=2 gcc-multilib g++-multilib
          .ci/riscv-toolchain-install.sh
          echo "$PWD/toolchain/bin" >> $GITHUB_PATH
      - name: Build binaries
        run: |
          make artifact ENABLE_PREBUILT=0
          mkdir -p /tmp/rv32emu-prebuilt
          mv build/sha1sum-linux-x86-softfp /tmp
          mv build/sha1sum-riscv32 /tmp
          mv build/linux-x86-softfp build/riscv32 /tmp/rv32emu-prebuilt
      - name: Create tarball
        run: |
          cd /tmp
          tar -zcvf rv32emu-prebuilt.tar.gz rv32emu-prebuilt
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.RV32EMU_PREBUILT_TOKEN }}
        run: |
          RELEASE_TAG="$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)-ELF"
          cd /tmp
          gh release create --latest=false $RELEASE_TAG \
            --repo sysprog21/rv32emu-prebuilt \
            --title "$RELEASE_TAG"
          gh release upload $RELEASE_TAG \
            rv32emu-prebuilt.tar.gz \
            sha1sum-linux-x86-softfp \
            sha1sum-riscv32 \
            --repo sysprog21/rv32emu-prebuilt
